version: '3.1'
services:
  mongo-express:
    image: mongo-express
    restart: always
    network_mode: host
    ports:
      - 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: sc2n7391PeFs3mKT
      ME_CONFIG_MONGODB_URL: mongodb://root:sc2n7391PeFs3mKT@localhost:27017/
